name: joke
description: Simple Flutter app task for showing joke
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.4
  intl: ^0.17.0
  get_it: ^7.2.0
  provider: ^6.0.2
  json_serializable: ^6.1.5
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
